const mongoose = require('mongoose')

const newsSchema = new mongoose.Schema({
    name :{
        uz:
        {
            type:String, 
            trim:true,
            minlength:10,
        },
        ru:{
            type:String, 
            trim:true,
            minlength:10,
        },
        eng:
        {
            type:String, 
            trim:true,
            minlength:10,
    }
    },
    title :{
        uz:
        {
            type:String, 
            trim:true,
            minlength:10,
        },
        ru:{
            type:String, 
            trim:true,
            minlength:10,
        },
        eng:
        {
            type:String, 
            trim:true,
            minlength:10,
    }
    },
    description :{
        uz:
        {
            type:String, 
            trim:true
        },
        uz1:
        {
            type:String, 
            trim:true
        },
        uz2:
        {
            type:String, 
            trim:true
        },
        uz3:
        {
            type:String, 
            trim:true
        },
        uz4:
        {
            type:String, 
            trim:true
        },
        uz5:
        {
            type:String, 
            trim:true
        },
        ru:{
            type:String, 
            trim:true
        },
        ru1:{
            type:String, 
            trim:true
        },
        ru2:{
            type:String, 
            trim:true
        },
        ru3:{
            type:String, 
            trim:true
        },
        ru4:{
            type:String, 
            trim:true
        },
        ru5:{
            type:String, 
            trim:true
        },
        eng:
        {
            type:String, 
            trim:true
        },
        eng1:
        {
            type:String, 
            trim:true
        },
        eng2:
        {
            type:String, 
            trim:true
        },
        eng3:
        {
            type:String, 
            trim:true
        },
        eng4:
        {
            type:String, 
            trim:true
        },
        eng5:
        {
            type:String, 
            trim:true
        }
    },
    actual:{
        type:Boolean,
        default:false
    },
    categoryID:{
        type: mongoose.Schema.ObjectId,
        ref:'Category',
        required:true
    },
    editor:{
        type:String,
        trim:true,
    },
    seen:{
        type:Number,
        default:0
    },
    poster:{
        min:{type:String, required:true},
        org:{type:String, required:true}
    },
    images:[
        {
        url:{
            type:String, 
            required:true}
        }
    ],
    videoLink:{
        type:String
    },
    imageInfo:{
        type:String,
    },
    tags: {
        type:String
    },
    search:{
        type:String
    }
},{
    timestamps:true
})

module.exports = mongoose.model('News', newsSchema)